INSERT INTO recipe (title, description, ingredients, instructions, prep_time, cook_time, servings, category, image_url, chef_id)
VALUES 
-- Protein-Rich Recipes
('Grilled Chicken Breast',
'Lean protein with herbs and spices',
'Chicken breast, Olive oil, Garlic, Rosemary, Thyme, Salt, Black pepper',
'1. Marinate chicken with herbs and oil\n2. Preheat grill\n3. Grill each side for 6-8 minutes\n4. Let rest before serving',
10,
16,
4,
'protein',
'/images/1-Grilled-Chicken-Breast-with-Herbs.jpg',
1),

('Baked Salmon',
'Omega-rich salmon with lemon and herbs',
'Salmon fillet, Lemon, Dill, Garlic, Olive oil, Salt, Pepper',
'1. Season salmon\n2. Add lemon and herbs\n3. Bake at 400°F\n4. Serve hot',
10,
20,
2,
'protein',
'/images/2-Pan-Seared-Salmon-with-Lemon.jpg',
1),

-- Carbohydrate Recipes
('Quinoa Power Bowl',
'Nutrient-rich quinoa with vegetables',
'Quinoa, Sweet potato, Black beans, Kale, Avocado, Olive oil, Lemon juice',
'1. Cook quinoa\n2. Roast vegetables\n3. Combine ingredients\n4. Add dressing',
15,
20,
2,
'carbs',
'/images/21-Quinoa-and-Turkey-Bowl-Prep.jpg',
1),

('Sweet Potato Mash',
'Creamy mashed sweet potatoes',
'Sweet potatoes, Butter, Milk, Cinnamon, Nutmeg, Salt',
'1. Boil sweet potatoes\n2. Mash with butter\n3. Add spices\n4. Mix until smooth',
10,
20,
4,
'carbs',
'/images/savory-mashed-sweet-potatoes-recipe-1.jpg',
1),


-- Vegetable Recipes
('Mediterranean Salad',
'Fresh vegetable salad with olive oil',
'Cucumber, Tomatoes, Red onion, Bell peppers, Olives, Feta cheese, Olive oil',
'1. Chop vegetables\n2. Mix ingredients\n3. Add dressing\n4. Toss well',
15,
0,
4,
'vegetables',
'/images/7-Mediterranean-Quinoa-Salad.jpg',
1),

('Roasted Vegetable Medley',
'Colorful roasted seasonal vegetables',
'Broccoli, Carrots, Brussels sprouts, Red onion, Garlic, Olive oil, Herbs',
'1. Cut vegetables\n2. Season with oil and herbs\n3. Roast until tender\n4. Serve hot',
15,
25,
4,
'vegetables',
'/images/20-Chicken-and-Sweet-Potato-Meal-Prep.jpg',
1),

-- Healthy Fats Recipes
('Avocado Toast',
'Classic avocado toast with toppings',
'Whole grain bread, Avocado, Cherry tomatoes, Red pepper flakes, Olive oil',
'1. Toast bread\n2. Mash avocado\n3. Add toppings\n4. Drizzle with oil',
10,
5,
2,
'healthy_fats',
'/images/10-Avocado-Toast-with-Poached-Egg.jpg',
1),

('Nuts and Seeds Mix',
'Energy-packed trail mix with premium nuts, seeds, and dried fruits',
'Almonds, Walnuts, Cashews, Pumpkin seeds, Sunflower seeds, Chia seeds, Dried cranberries, Raisins, Dark chocolate chips (optional)',
'1. Toast nuts and seeds in a dry pan until fragrant (3-5 minutes)\n2. Let cool completely\n3. Mix all nuts and seeds in a large bowl\n4. Add dried fruits and chocolate chips if using\n5. Store in an airtight container\n6. Will keep fresh for up to 2 weeks',
10,
5,
8,
'healthy_fats',
'/images/14-Nuts-and-Seeds-Mix.jpg',
1),

-- Smoothies & Drinks
('Green Power Smoothie',
'Nutrient-packed green smoothie',
'Spinach, Banana, Apple, Ginger, Almond milk, Chia seeds, Honey',
'1. Add ingredients to blender\n2. Blend until smooth\n3. Add ice if desired',
5,
0,
2,
'smoothies',
'/images/18Green-Protein-Smoothie.jpg',
1),

('Berry Blast Smoothie',
'Antioxidant-rich berry smoothie',
'Mixed berries, Yogurt, Honey, Almond milk, Banana, Flax seeds',
'1. Blend berries and banana\n2. Add remaining ingredients\n3. Blend until smooth',
5,
0,
2,
'smoothies',
'/images/19-Berry-Protein-Blast.jpg',
1),

-- Healthy Snacks
('Energy Balls',
'No-bake energy balls',
'Dates, Oats, Peanut butter, Chia seeds, Dark chocolate chips, Honey',
'1. Process dates\n2. Mix ingredients\n3. Form balls\n4. Chill',
15,
0,
12,
'snacks',
'/images/13-Protein-Energy-Balls.jpg',
1),

('Hummus with Veggie Sticks',
'Classic hummus with fresh vegetables',
'Chickpeas, Tahini, Garlic, Lemon, Olive oil, Carrots, Celery, Cucumber',
'1. Blend hummus ingredients\n2. Cut vegetables\n3. Serve together',
10,
0,
4,
'snacks',
'/images/15-Homemade-Hummus.jpg',
1);
