
-- Insert more recipes
INSERT INTO recipe (
    title, description, ingredients, instructions, prep_time, cook_time, 
    servings, category, image_url, chef_id, difficulty_level, cuisine_type, 
    dietary_restrictions, calories, protein, carbs, fats
) VALUES 
(
    'Grilled Salmon with Asparagus',
    'A healthy and delicious salmon dish with perfectly grilled asparagus',
    'salmon fillet,asparagus,olive oil,lemon,garlic,salt,black pepper,fresh dill',
    'Season salmon with salt, pepper, and garlic\nPreheat grill to medium-high\nGrill salmon for 4-5 minutes per side\nToss asparagus with olive oil and seasonings\nGrill asparagus for 3-4 minutes\nServe with lemon wedges and fresh dill',
    15,
    20,
    4,
    'Dinner',
    'https://images.unsplash.com/photo-1467003909585-2f8a72700288',
    1,
    'Medium',
    'Seafood',
    'Gluten-free, Dairy-free',
    320,
    34,
    8,
    18
),
(
    'Breakfast Smoothie Bowl',
    'Start your day with this nutritious and Instagram-worthy smoothie bowl',
    'frozen mixed berries,banana,Greek yogurt,almond milk,honey,granola,chia seeds,fresh fruit for topping',
    'Blend frozen berries, banana, yogurt, and almond milk until smooth\nPour into a bowl\nTop with granola, fresh fruit, and chia seeds\nDrizzle with honey',
    10,
    0,
    1,
    'Breakfast',
    'https://images.unsplash.com/photo-1511690078903-71dc5a49f5e3',
    1,
    'Easy',
    'International',
    'Vegetarian',
    280,
    12,
    45,
    8
),
(
    'Homemade Pizza Margherita',
    'Classic Italian pizza with fresh mozzarella and basil',
    'pizza dough,tomato sauce,fresh mozzarella,fresh basil,olive oil,salt,black pepper',
    'Preheat oven to 450°F with pizza stone\nStretch dough into circle\nSpread sauce and add cheese\nBake for 12-15 minutes\nTop with fresh basil',
    30,
    15,
    4,
    'Dinner',
    'https://images.unsplash.com/photo-1574071318508-1cdbab80d002',
    1,
    'Medium',
    'Italian',
    'Vegetarian',
    285,
    12,
    38,
    10
),
(
    'Quinoa Buddha Bowl',
    'A nutritious bowl packed with protein and vegetables',
    'quinoa,sweet potato,chickpeas,kale,avocado,tahini,lemon juice,olive oil,cumin,paprika',
    'Cook quinoa according to package\nRoast sweet potato and seasoned chickpeas\nMassage kale with olive oil\nAssemble bowl with all ingredients\nDrizzle with tahini dressing',
    20,
    25,
    2,
    'Lunch',
    'https://images.unsplash.com/photo-1490645935967-10de6ba17061',
    1,
    'Easy',
    'International',
    'Vegan, Gluten-free',
    420,
    15,
    52,
    22
);